In [102]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier

datapd = pd.read_csv('data\\1day\\000001.csv')
datapd = datapd.iloc[:,1:]
datapd

open   high  close    low      volume  price_change  p_change     ma5  \
0    13.21  13.43  13.30  13.10   982915.50          0.09      0.68  13.342   
1    13.28  13.46  13.21  13.02  1553030.38         -0.08     -0.60  13.386   
2    13.58  13.78  13.29  13.19  1366566.75         -0.37     -2.71  13.452   
3    13.26  13.69  13.66  13.19  1123688.50          0.41      3.09  13.446   
4    13.52  13.86  13.25  13.16  1585567.25         -0.27     -2.00  13.370   
5    13.50  13.63  13.52  13.45   742900.94         -0.02     -0.15  13.270   
6    13.18  13.68  13.54  13.16  1485203.50          0.28      2.11  13.110   
7    13.20  13.31  13.26  13.13  1106245.00         -0.02     -0.15  13.002   
8    12.79  13.32  13.28  12.74  2397943.00          0.53      4.16  12.976   
9    12.73  12.91  12.75  12.64   805464.50          0.03      0.24  12.924   
10   12.90  12.93  12.72  12.67  1099952.50         -0.28     -2.15  13.074   
11   13.15  13.31  13.00  12.91  1001998.00         -0.13     -0.99  13.148   
12   13.00  13.20  13.13  12.88  1289248.12          0.11      0.84  13.114   
13   13.40  13.48  13.02  13.02  1743405.75         -0.48     -3.56  13.104   
14   13.08  13.57  13.50  12.88  2261952.75          0.41      3.13  13.160   
15   12.89  13.09  13.09  12.75  1351315.00          0.26      2.03  13.120   
16   13.05  13.14  12.83  12.75  1181957.88         -0.25     -1.91  13.102   
17   13.26  13.27  13.08  12.79  1619845.00         -0.22     -1.65  13.212   
18   13.15  13.49  13.30  13.10  1723681.25          0.00      0.00  13.360   
19   13.05  13.37  13.30  13.00  1454023.50          0.30      2.31  13.440   
20   13.40  13.48  13.00  12.96  1784933.12         -0.38     -2.84  13.566   
21   13.70  13.73  13.38  13.26  1379635.62         -0.44     -3.18  13.878   
22   13.73  13.93  13.82  13.47  1564094.88          0.12      0.88  14.072   
23   13.85  13.85  13.70  13.40  1766432.50         -0.23     -1.65  14.328   
24   14.30  14.30  13.93  13.75  2064085.25         -0.63     -4.33  14.478   
25   14.29  14.59  14.56  13.78  2630189.50          0.21      1.46  14.542   
26   15.15  15.24  14.35  14.07  2429142.00         -0.75     -4.97  14.266   
27   14.48  15.24  15.10  14.48  2570231.50          0.65      4.50  14.016   
28   14.07  14.79  14.45  14.01  2495327.75          0.20      1.40  13.576   
29   13.13  14.25  14.25  13.05  2843925.75          1.07      8.12  13.276   
..     ...    ...    ...    ...         ...           ...       ...     ...   
689  14.20  14.96  14.60  14.08  3305137.25          0.74      5.34  13.964   
690  13.79  14.08  13.86  13.79   903354.12          0.09      0.65  13.720   
691  14.00  14.12  13.77  13.77  1385706.25         -0.38     -2.69  13.662   
692  13.47  14.34  14.15  13.32  2205323.50          0.71      5.28  13.628   
693  13.37  13.51  13.44  13.35   557047.75          0.06      0.45  13.604   
694  13.50  13.53  13.38  13.29   828604.88         -0.19     -1.40  13.714   
695  13.62  13.72  13.57  13.50   814973.06         -0.03     -0.22  13.852   
696  13.98  13.98  13.60  13.59  1059476.25         -0.43     -3.06  13.898   
697  14.03  14.09  14.03  13.87  1018797.00          0.04      0.29  14.254   
698  14.06  14.16  13.99  13.96   793570.12         -0.08     -0.57  14.246   
699  13.80  14.08  14.07  13.60  1025544.25          0.27      1.96  14.232   
700  14.04  14.05  13.80  13.76   577392.31         -0.19     -1.36  14.208   
701  14.07  15.39  15.38  14.01    66052.74          1.39      9.94  14.220   
702  13.96  14.11  13.99  13.93   680491.56          0.07      0.50  13.890   
703  13.95  14.01  13.92  13.73   721202.38         -0.03     -0.21  13.846   
704  13.93  14.18  13.95  13.84   887743.12          0.09      0.65  13.766   
705  13.75  13.90  13.86  13.62   608715.69          0.13      0.95  13.678   
706  13.78  13.85  13.73  13.68   554349.50         -0.04     -0.29  13.664   
707  13.49  13.82  13.77  13.42   724875.38          0.2

In [55]:
p = pd.Series(datapd.loc[:,"price_change"])
datapd['pc'] = p > 0
datapd

RangeIndex(start=0, stop=719, step=1)


open   high  close    low      volume  price_change  p_change     ma5  \
0    13.21  13.43  13.30  13.10   982915.50          0.09      0.68  13.342   
1    13.28  13.46  13.21  13.02  1553030.38         -0.08     -0.60  13.386   
2    13.58  13.78  13.29  13.19  1366566.75         -0.37     -2.71  13.452   
3    13.26  13.69  13.66  13.19  1123688.50          0.41      3.09  13.446   
4    13.52  13.86  13.25  13.16  1585567.25         -0.27     -2.00  13.370   
5    13.50  13.63  13.52  13.45   742900.94         -0.02     -0.15  13.270   
6    13.18  13.68  13.54  13.16  1485203.50          0.28      2.11  13.110   
7    13.20  13.31  13.26  13.13  1106245.00         -0.02     -0.15  13.002   
8    12.79  13.32  13.28  12.74  2397943.00          0.53      4.16  12.976   
9    12.73  12.91  12.75  12.64   805464.50          0.03      0.24  12.924   
10   12.90  12.93  12.72  12.67  1099952.50         -0.28     -2.15  13.074   
11   13.15  13.31  13.00  12.91  1001998.00         -0.13     -0.99  13.148   
12   13.00  13.20  13.13  12.88  1289248.12          0.11      0.84  13.114   
13   13.40  13.48  13.02  13.02  1743405.75         -0.48     -3.56  13.104   
14   13.08  13.57  13.50  12.88  2261952.75          0.41      3.13  13.160   
15   12.89  13.09  13.09  12.75  1351315.00          0.26      2.03  13.120   
16   13.05  13.14  12.83  12.75  1181957.88         -0.25     -1.91  13.102   
17   13.26  13.27  13.08  12.79  1619845.00         -0.22     -1.65  13.212   
18   13.15  13.49  13.30  13.10  1723681.25          0.00      0.00  13.360   
19   13.05  13.37  13.30  13.00  1454023.50          0.30      2.31  13.440   
20   13.40  13.48  13.00  12.96  1784933.12         -0.38     -2.84  13.566   
21   13.70  13.73  13.38  13.26  1379635.62         -0.44     -3.18  13.878   
22   13.73  13.93  13.82  13.47  1564094.88          0.12      0.88  14.072   
23   13.85  13.85  13.70  13.40  1766432.50         -0.23     -1.65  14.328   
24   14.30  14.30  13.93  13.75  2064085.25         -0.63     -4.33  14.478   
25   14.29  14.59  14.56  13.78  2630189.50          0.21      1.46  14.542   
26   15.15  15.24  14.35  14.07  2429142.00         -0.75     -4.97  14.266   
27   14.48  15.24  15.10  14.48  2570231.50          0.65      4.50  14.016   
28   14.07  14.79  14.45  14.01  2495327.75          0.20      1.40  13.576   
29   13.13  14.25  14.25  13.05  2843925.75          1.07      8.12  13.276   
..     ...    ...    ...    ...         ...           ...       ...     ...   
689  14.20  14.96  14.60  14.08  3305137.25          0.74      5.34  13.964   
690  13.79  14.08  13.86  13.79   903354.12          0.09      0.65  13.720   
691  14.00  14.12  13.77  13.77  1385706.25         -0.38     -2.69  13.662   
692  13.47  14.34  14.15  13.32  2205323.50          0.71      5.28  13.628   
693  13.37  13.51  13.44  13.35   557047.75          0.06      0.45  13.604   
694  13.50  13.53  13.38  13.29   828604.88         -0.19     -1.40  13.714   
695  13.62  13.72  13.57  13.50   814973.06         -0.03     -0.22  13.852   
696  13.98  13.98  13.60  13.59  1059476.25         -0.43     -3.06  13.898   
697  14.03  14.09  14.03  13.87  1018797.00          0.04      0.29  14.254   
698  14.06  14.16  13.99  13.96   793570.12         -0.08     -0.57  14.246   
699  13.80  14.08  14.07  13.60  1025544.25          0.27      1.96  14.232   
700  14.04  14.05  13.80  13.76   577392.31         -0.19     -1.36  14.208   
701  14.07  15.39  15.38  14.01    66052.74          1.39      9.94  14.220   
702  13.96  14.11  13.99  13.93   680491.56          0.07      0.50  13.890   
703  13.95  14.01  13.92  13.73   721202.38         -0.03     -0.21  13.846   
704  13.93  14.18  13.95  13.84   887743.12          0.09      0.65  13.766   
705  13.75  13.90  13.86  13.62   608715.69          0.13      0.95  13.678   
706  13.78  13.85  13.73  13.68   554349.50         -0.04     -0.29  13.664   
707  13.49  13.82  13.77  13.42   724875.38          0.2

In [74]:
from compiler.ast import flatten
dataset = np.matrix(datapd.iloc[:,1:])
X = dataset[:,:13]
y = map(lambda x: map(int, x), dataset[:,13])
y = np.array(y).ravel()
print X
print y

[[13.43 13.3 13.1 ..., 1314952.53 1393845.25 0.58]
 [13.46 13.21 13.02 ..., 1326656.23 1433946.13 0.92]
 [13.78 13.29 13.19 ..., 1271552.99 1425276.4 0.81]
 ..., 
 [14.3 14.06 13.8 ..., 1212659.29 1212659.29 1.26]
 [14.37 13.99 13.83 ..., 1198550.19 1198550.19 1.36]
 [14.44 14.34 14.16 ..., 1057605.75 1057605.75 1.08]]
[1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 1
 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1
 0 1 0 1 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 1 1 1
 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0 1
 1 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 1
 1 0 0 1 0 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0
 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 0 0 1 1 0
 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1
 0 1

In [47]:
from sklearn import preprocessing

normalized_X = preprocessing.normalize(X)
print normalized_X
standardized_X = preprocessing.scale(X)
standardized_X

[[  1.88083892e-04   1.88467215e-04   1.88211666e-04 ...,   5.10702708e-01
    5.09863231e-01   2.55548766e-07]
 [  1.66749133e-04   1.67089437e-04   1.66976002e-04 ...,   4.55884188e-01
    4.45568429e-01   3.40304352e-07]
 [  1.65044275e-04   1.65268672e-04   1.65044275e-04 ...,   4.31717002e-01
    4.22612078e-01   3.36596074e-07]
 ..., 
 [  1.29594411e-04   1.29594411e-04   1.29118311e-04 ...,   5.91592298e-01
    3.83284279e-01   2.85659981e-07]
 [  1.15076123e-04   1.15160613e-04   1.14991632e-04 ...,   5.09432363e-01
    3.28962248e-01   2.53471636e-07]
 [  1.16407327e-04   1.16492607e-04   1.16151486e-04 ...,   4.83874129e-01
    3.12734892e-01   2.55840278e-07]]


array([[ 1.01899246,  0.98193034,  1.04170396, ..., -0.3039667 ,
        -0.39177329, -0.36321295],
       [ 0.97189652,  0.93573727,  1.01805556, ..., -0.29602254,
        -0.42112861,  0.06896448],
       [ 0.99544449,  0.93573727,  0.99440715, ..., -0.35781363,
        -0.49706086,  0.06896448],
       ..., 
       [-1.59483216, -1.65107462, -1.72515971, ...,  0.49622285,
        -0.3753424 ,  0.06896448],
       [-1.5712842 , -1.60488155, -1.60691767, ...,  0.42998303,
        -0.43736182,  0.06896448],
       [-1.50064029, -1.53559195, -1.58326927, ...,  0.30160547,
        -0.54388724,  0.06896448]])

In [81]:
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y)
x = model.predict(X)
print x + y
print model.feature_importances_

[2 0 0 2 0 0 2 0 2 2 0 0 2 0 2 2 0 0 0 2 0 0 2 0 0 2 0 2 2 2 2 2 0 2 2 0 2
 2 2 0 0 2 0 0 0 2 0 0 2 0 0 0 2 0 2 0 2 2 2 2 2 0 0 0 0 0 2 2 0 0 0 0 0 2
 0 2 0 2 0 2 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 2 0 2 0 2 2 0 2 0 0 2 2 2
 0 2 2 0 0 2 2 2 2 2 2 2 0 2 0 0 2 2 2 0 2 2 0 2 0 0 0 2 0 2 0 2 2 0 0 0 2
 2 0 2 2 2 0 0 0 0 0 0 2 2 2 2 0 0 0 0 0 2 0 0 2 0 2 2 0 0 2 0 0 0 0 0 0 0
 2 2 0 0 0 0 0 2 0 0 0 0 2 2 0 2 2 0 0 0 2 0 0 2 2 0 0 0 0 2 2 0 2 2 0 2 2
 2 0 0 2 0 2 2 0 2 0 2 2 2 2 0 2 2 0 0 2 0 2 0 2 2 2 0 0 2 0 0 2 0 0 0 0 0
 0 0 2 2 0 2 0 0 2 0 0 2 2 2 2 2 2 0 0 0 2 2 2 2 0 2 2 0 2 0 2 2 0 0 2 2 0
 0 2 0 2 0 0 2 2 2 2 0 2 0 0 2 0 0 2 0 2 0 0 0 0 0 0 0 0 2 2 0 2 2 2 0 0 2
 0 2 0 2 2 2 0 2 2 2 0 0 0 2 2 2 0 2 2 0 2 0 0 2 2 0 2 2 2 0 0 0 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 2 0 0 2 2 2 0 0 2 2 2 0 2 0 0 2 0 0 0 2 0 2 2 0 0 0 0
 2 2 0 2 0 2 0 2 0 0 2 0 2 2 2 0 2 0 0 2 2 2 0 2 0 0 2 0 0 0 2 2 2 2 2 2 2
 0 0 0 0 2 2 2 2 0 2 0 2 0 2 0 0 2 2 0 0 2 0 2 0 2 0 2 0 0 2 0 0 2 0 0 2 0
 2 0 2 0 2 2 0 0 2 2 0 2 

In [ ]:
print model.predict

In [91]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(X, y)
x = rfe.predict(X)
print (x + y).tolist().count(1) / float(len(x))
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

0.376912378303
[False False False  True False False False False False  True False  True
 False]
[10  5 11  1  4  3  8  7  6  1  2  1  9]


In [95]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
#print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

          0       0.60      0.71      0.65       356
          1       0.65      0.53      0.59       363

avg / total       0.63      0.62      0.62       719

[[253 103]
 [170 193]]


In [96]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

          0       0.52      0.84      0.64       356
          1       0.60      0.23      0.34       363

avg / total       0.56      0.53      0.49       719

[[299  57]
 [278  85]]


In [97]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

          0       0.72      0.78      0.74       356
          1       0.76      0.70      0.73       363

avg / total       0.74      0.74      0.74       719

[[276  80]
 [110 253]]


In [98]:
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       356
          1       1.00      1.00      1.00       363

avg / total       1.00      1.00      1.00       719

[[356   0]
 [  0 363]]


In [99]:
from sklearn import metrics
from sklearn.svm import SVC
# fit a SVM model to the data
model = SVC()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       356
          1       1.00      1.00      1.00       363

avg / total       1.00      1.00      1.00       719

[[356   0]
 [  0 363]]


In [100]:
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.grid_search import GridSearchCV
# prepare a range of alpha values to test
alphas = np.array([1,0.1,0.01,0.001,0.0001,0])
# create and fit a ridge regression model, testing each alpha
model = Ridge()
grid = GridSearchCV(estimator=model, param_grid=dict(alpha=alphas))
grid.fit(X, y)
print(grid)
# summarize the results of the grid search
print(grid.best_score_)
print(grid.best_estimator_.alpha)

C:\ProgramData\Anaconda2\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


GridSearchCV(cv=None, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'alpha': array([  1.00000e+00,   1.00000e-01,   1.00000e-02,   1.00000e-03,
         1.00000e-04,   0.00000e+00])},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)
0.226743398089
1.0


In [101]:
import numpy as np
from scipy.stats import uniform as sp_rand
from sklearn.linear_model import Ridge
from sklearn.grid_search import RandomizedSearchCV
# prepare a uniform distribution to sample for the alpha parameter
param_grid = {'alpha': sp_rand()}
# create and fit a ridge regression model, testing random alpha values
model = Ridge()
rsearch = RandomizedSearchCV(estimator=model, param_distributions=param_grid, n_iter=100)
rsearch.fit(X, y)
print(rsearch)
# summarize the results of the random parameter search
print(rsearch.best_score_)
print(rsearch.best_estimator_.alpha)

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
          fit_params={}, iid=True, n_iter=100, n_jobs=1,
          param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000000000C113940>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          scoring=None, verbose=0)
0.226719533844
0.999673395954
